import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { Providers } from "./Providers";

import TopNavBar from "./_components/TopNavBar";

export const metadata: Metadata = {
  title: "AirTable Clone",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="min-h-screen w-full">
        <Providers>
          {/* <TopNavBar/> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
